project:
  type: website
  output-dir: _site

website:
  sidebar: false
  navbar: false

format:
  html:
    theme: cosmo
    page-layout: full
    toc: true
    toc-depth: 2
    toc-location: right
    number-sections: true
  pdf:
    pdf-engine: xelatex
